import {
  Activity,
  AlarmClock,
  Anchor,
  Archive,
  Armchair,
  ArrowLeft,
  ArrowRight,
  Award,
  Baby,
  Backpack,
  Banknote,
  BarChart2,
  Beaker,
  Bell,
  BellRing,
  Bike,
  Bird,
  Bluetooth,
  BookMarked,
  Box,
  BookOpen,
  Bookmark,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cast,
  Check,
  CheckCircle,
  CheckCircle2,
  ChefHat,
  ChevronRight,
  CircuitBoard,
  Clipboard,
  Clock,
  Cloud,
  CloudLightning,
  Code,
  Coffee,
  Coins,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Dumbbell,
  Edit,
  Eye,
  EyeOff,
  File,
  Film,
  Fingerprint,
  Flag,
  Flame,
  Folder,
  Gamepad,
  Gauge,
  Gem,
  GitBranch,
  GitPullRequest,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  HelpCircle,
  Hexagon,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Layers,
  Layout,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinCheck,
  Medal,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mouse,
  Music,
  Newspaper,
  Palette,
  Paperclip,
  Pause,
  Pencil,
  PenTool,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PieChart,
  Play,
  Plug,
  Plus,
  Power,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  Receipt,
  RefreshCcw,
  Repeat,
  Rocket,
  Ruler,
  Scale,
  Scan,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Signal,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Sun,
  Tablet,
  Tag,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trash,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Upload,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Wand2,
  Watch,
  Wifi,
  Wind,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Named icon registry for hero stat cards (`HeroStat.iconName`) and every other
 * icon-picking section (cards, two-column, careers, life). JSON content can't
 * carry a component reference, so sections store a string key that maps to a
 * real lucide-react icon here — same approach as
 * `lib/service-category-icons.tsx` for card icons, just backed by lucide
 * directly instead of hand-rolled SVGs.
 *
 * The pool is intentionally large (176 icons) so admins can pick from a wide
 * visual vocabulary in the Landing Page editor / section forms via the
 * "Site Icons" dropdown, which is seeded from these keys by
 * `app/actions/icons.ts` (`site-icons` Setting).
 *
 * Only keys present here are safe to reference — an unknown name resolves to
 * `null` and the badge renders without an icon.
 */
export const HERO_STAT_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  anchor: Anchor,
  archive: Archive,
  armchair: Armchair,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  award: Award,
  baby: Baby,
  backpack: Backpack,
  banknote: Banknote,
  "bar-chart-2": BarChart2,
  beaker: Beaker,
  bell: Bell,
  "bell-ring": BellRing,
  bike: Bike,
  bird: Bird,
  bluetooth: Bluetooth,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bookmark: Bookmark,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  brush: Brush,
  bug: Bug,
  building: Building,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  cast: Cast,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle-2": CheckCircle2,
  "chef-hat": ChefHat,
  "chevron-right": ChevronRight,
  "circuit-board": CircuitBoard,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  "cloud-lightning": CloudLightning,
  code: Code,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  "dollar-sign": DollarSign,
  dumbbell: Dumbbell,
  edit: Edit,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  film: Film,
  fingerprint: Fingerprint,
  flag: Flag,
  flame: Flame,
  folder: Folder,
  gamepad: Gamepad,
  gauge: Gauge,
  gem: Gem,
  "git-branch": GitBranch,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  handshake: Handshake,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "help-circle": HelpCircle,
  hexagon: Hexagon,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  lamp: Lamp,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  layout: Layout,
  leaf: Leaf,
  lightbulb: Lightbulb,
  link: Link,
  "list-checks": ListChecks,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  "map-pin-check": MapPinCheck,
  medal: Medal,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  mouse: Mouse,
  music: Music,
  newspaper: Newspaper,
  palette: Palette,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  "pen-tool": PenTool,
  phone: Phone,
  "phone-call": PhoneCall,
  "phone-incoming": PhoneIncoming,
  "pie-chart": PieChart,
  play: Play,
  plug: Plug,
  plus: Plus,
  power: Power,
  presentation: Presentation,
  printer: Printer,
  puzzle: Puzzle,
  "qr-code": QrCode,
  receipt: Receipt,
  "refresh-ccw": RefreshCcw,
  repeat: Repeat,
  rocket: Rocket,
  ruler: Ruler,
  scale: Scale,
  scan: Scan,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "settings-2": Settings2,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  signal: Signal,
  smartphone: Smartphone,
  smile: Smile,
  snowflake: Snowflake,
  sparkles: Sparkles,
  speaker: Speaker,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  timer: Timer,
  trash: Trash,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  umbrella: Umbrella,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  users: Users,
  video: Video,
  wallet: Wallet,
  "wand-2": Wand2,
  watch: Watch,
  wifi: Wifi,
  wind: Wind,
  wrench: Wrench,
  "x-circle": XCircle,
  zap: Zap,
};

export function getHeroStatIcon(name?: string): LucideIcon | null {
  if (!name) return null;
  return HERO_STAT_ICONS[name] ?? null;
}